version: '{build}'
init:
- ps: Update-AppveyorBuild -Version "1.0.$((Get-Date -format yyyyMM) + ([string]$env:appveyor_build_number).PadLeft(2, '0'))"
branches:
  only:
  - master
image:
- Visual Studio 2015
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: x64\Release\
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: ZZCq96B9Lu5V9my8skzCnvolhnB7IWT0ubWTa06j7RHVF5VaaO19JI4LyLiaxP/q
  artifact: Release
