version: '{build}'
init:
        - ps: Update-AppveyorBuild -Version "1.0.$(Get-Date -format yyyyMM + '{0:00}' -f $env:appveyor_build_number)"
branches:
  only:
  - master
image:
- Visual Studio 2015
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: x64\Release\
  name: Release
deploy:
- provider: GitHub
  auth_token:
    secure: A76YZrze6xopKjjUoIVUa7dAVmnQFEYGK614uKMLY9WxswlFE5dR1rslJaMtSi7z 
  artifact: Release
